echo "MESSAGE=${MESSAGE}" > .env
echo "ACCESS_KEY=${ACCESS_KEY}" >> .env
echo "SECRET_KEY=${SECRET_KEY}" >> .env
echo "SESSION_TOKEN=FwoGZXIvYXdzEDYaDI69G/nd1XBIoeWRUiLHAfEy4HJJLlbmt/m2FayA42s/fv8pq2MQITIDIRRebF3NxEliRYnOIfxGJNALdsV7oZ6yUqyjx7CBhiJxQyAYsRuoJfODBES6Z1ccITz9CPaPOYF7yC80gpzKdAVa4vKd/ljE131MEoJMOZHFLnX1YfyRxR/ZjjkD0GIpOPSLseODs0i0CGz6tIsojj2OrjKu9RM3chens4wtCOt3blcWY9TTqCbMkIyv6dFDkd4TQnR/Y3LrP29PE3zoAGwaqvUW0q+NulfNx2wohLuUhgYyLTtbzit9OiNehPvEVtRudl0/2hWJlk/+Q3G8HB8YtgzE/Zm24sea+fvZh7BOww==" >> .env
echo "BUCKET_NAME=${BUCKET_NAME}" >> .env
