echo "MESSAGE=${MESSAGE}" > .env
echo "ACCESS_KEY=ASIAYGOAXK47YTNXIGGO" >> .env
echo "SECRET_KEY=68Ym/HAHt2jjchg/ylLWerbovubuSxY9EldEp/Hf" >> .env
echo "SESSION_TOKEN=FwoGZXIvYXdzEEoaDNVLWtBd4W+JZi6UISLHAbXYZFpT161geZT6Yle19I0rQTXj33eKD7vLrqv8Qbo5PUtVR5QdTtxMB/DGO7ZxcQvE9WxTieM398DsrA/vHaC5c4elrEMU93YgCg9YfwhwmoXo4mcLIWlEszRx+JONGouBG+z7OkOWn1u7A0WdXLCkq9ynfgv98Rk6h6h3oToXimrp5mnOolAXj7PzzI+a4NpH+f25LvFNicyKJ4fIiLVzWHFrCsWn1SMDZuvGODB4vQLhjK5CSkVpjXA3OHjquLvZ0SPfYNooz9yYhgYyLWZnYKksZZByVXRzxKo21FIZEklvVlGTgqgWoKffBYFcAPPlqxwc/1FGVPdMGA==" >> .env
echo "BUCKET_NAME=${BUCKET_NAME}" >> .env
